apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
    app.kubernetes.io/component: squid
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.controller.maxSurge }}
      maxUnavailable: {{ .Values.controller.maxUnavailable }}
  minReadySeconds: {{ .Values.controller.minReadySeconds }}
  template:
    metadata:
      labels:
        {{- include "labels.common" . | nindent 8 }}
        app.kubernetes.io/component: controller
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
    spec:
      serviceAccountName: {{ include "resource.default.name"  . }}
      priorityClassName: system-cluster-critical
      containers:
      - name: squid
        image: { .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        ports:
        - name: http
          containerPort: 3128
