apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
    app.kubernetes.io/component: squid
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.controller.maxSurge }}
      maxUnavailable: {{ .Values.controller.maxUnavailable }}
  minReadySeconds: {{ .Values.controller.minReadySeconds }}
  template:
    metadata:
      labels:
        {{- include "labels.common" . | nindent 8 }}
        app.kubernetes.io/component: controller
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
    spec:
      serviceAccountName: {{ include "name"  . }}
      priorityClassName: system-cluster-critical
      securityContext:
        fsGroup: 0
        supplementalGroups:
        - 0
        {{- with .Values.podSecurityContext }}
          {{- . | toYaml | nindent 8 }}
        {{- end }}
      containers:
      - name: squid
        image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        ports:
        - name: http
          containerPort: 3128
        securityContext:
          {{- with .Values.securityContext }}
            {{- . | toYaml | nindent 12 }}
          {{- end }}
      volumeMounts:
        - mountPath: /etc/squid/conf.d/
          name: conf
      volumes:
      - name: conf
        configMap:
          name: {{ include "resource.default.name" . }}-squid-configuration

