{{- if .Values.podSecurityPolicy.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "resource.default.name" . }}-psp-user
  labels:
    {{- include "labels.common" . | nindent 4 }}
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ include "resource.default.name" . }}
  verbs:
  - use
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "resource.default.name" . }}-psp
  labels:
    {{- include "labels.common" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "resource.default.name" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "resource.default.name" . }}-psp-user
  apiGroup: rbac.authorization.k8s.io
{{- end }}
