apiVersion: v1
kind: ServiceAccount
metadata:
  name: squid
  namespace: default
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: squid
  namespace: default
spec:
  allowPrivilegeEscalation: true
  privileged: true
  hostNetwork: true
  hostPorts:
  - min: 3128
    max: 3128
  allowedCapabilities:
  - NET_BIND_SERVICE
  runAsUser:
    rule: MustRunAs
    ranges:
      - min: 0
        max: 65535
  runAsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 0
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 0
        max: 65535
  volumes:
  - 'secret'
  - 'configMap'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: squid-psp-use
  namespace: default
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - squid
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: squid-psp-use
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: squid-psp-use
subjects:
- kind: ServiceAccount
  name: squid
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid
spec:
  selector:
    matchLabels:
      app: squid
  replicas: 1
  template:
    metadata:
      labels:
        app: squid
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Exists
        key: node.kubernetes.io/not-ready
      hostNetwork: true
      serviceAccountName: squid
      containers:
      - name: squid
        image: ubuntu/squid:5.2-22.04_beta
        ports:
        - name: http
          containerPort: 3128
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: squid
  name: squid
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: http
    port: 4000
    protocol: TCP
    targetPort: http
  selector:
    app: squid
  type: LoadBalancer
